model_reasoning_effort = "high"
hide_agent_reasoning = true
network_access = true
web_search = 'live'
notify = ["bash", "-lc", "say '終わったよ'"]

[mcp_servers.context7]
command = "npx"
args = ["-y", "@upstash/context7-mcp@latest"]